version: '3'
services: 
    spark:
        image: bitnami/spark
        container_name: spark
        network_mode: 'bridge'
        tty: true
        environment:
            SPARK_MODE: 'master'
        volumes:
            - ./data:/opt/bitnami/spark/data/
            - ./scripts:/opt/bitnami/spark/script/