version: '3'
services: 
    jupyterpsnb:
        image: jupyter/pyspark-notebook
        container_name: jupyterpsnb
        ports: 
            - 8888:8888
        volumes: 
            - './data/jupyter-pyspark:/home/jovyan/work'
            - './scripts:/home/scripts/'
        user: root
        network_mode: 'bridge'
