version: '3'
services: 
    jupyterpsnb:
        image: jupyter/pyspark-notebook
        container_name: jupyterpsnb
        ports: 
            - 8888:8888
        volumes: 
            - './data:/home/jovyan/work'
            - './scripts:/home/scripts/'
            #- './opt:/opt/conda/lib/python3.7/site-packages/'
        user: root
        network_mode: 'bridge'
