version: '3'
services: 
    mongo:
        image: 'mongo'
        container_name: mongo
        ports: 
            - 27017:27017
        volumes: 
            # - './mongod.conf:/etc/mongo/mongod.conf'
            - './data/db:/data/db'
        # command: 
        #     - '-f'
        #     - '/etc/mongo/mongod.conf'
