version: '3'
services: 
    postgres:
        image: postgres
        container_name: postgres
        network_mode: 'bridge'
        ports: 
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes: 
            - './data:/var/lib/postgresql/data'
